{% set version = "17.8.2" %}

package:
  name: cptbin
  version: {{ version }}

source:
  url: https://academiccommons.columbia.edu/doi/10.7916/wehb-sq76/download
  fn: CPT.{{ version }}.tar.gz
  sha256: a6ec2dd00aee284cce2834359cd467dbbad5e87450b0a1db8c77889f8ef28118
  patches:
    - patch

build:
  number: 2

requirements:
  build:
    - make
    - {{ compiler('fortran') }}

    # I think this is the default when building with conda-smithy, but
    # when building manually with conda-build it's easy to forget to
    # exclude the defaults channels and end up with a mix of centos
    # packages from conda-forge and centos7 packages from defaults,
    # resulting in a failed build. In that situation, this constraint
    # makes the build fail faster so you can fix the command line.
    - sysroot_linux-64 2.12  # [linux64]

test:
  commands:
    - echo 0 | $CONDA_PREFIX/bin/CPT.x | grep "International Research Institute"

about:
  home: https://iri.columbia.edu/our-expertise/climate/tools/cpt/
  summary: 'The Climate Predictability Tool'
  description: |
    The Climate Predictability Tool (CPT) is a software package for
    constructing a seasonal climate forecast model, performing model
    validation, and producing forecasts given updated data. Its design
    has been tailored for producing seasonal climate forecasts using
    model output statistic (MOS) corrections to climate predictions
    from general circulation model (GCM), or for producing forecasts
    using fields of sea-surface temperatures or similar
    predictors. Although the software is specifically tailored for
    these applications, it can be used in more general settings to
    perform canonical correlation analysis (CCA), principal components
    regression (PCR), or multiple linear regression (MLR) on any data,
    and for any application.
  license_file:
    - {{ version }}/LICENSE
    - {{ version }}/lapack/lapack/LICENSE
